package tn.banque.Entities;

public enum TypeEmployee {
	GESTIONNAIRE_CLIENTELE,GESTIONNAIRE_PATRIMOINE,
	CONSEILLER,CONTROLLEUR_GESTION,PARTENAIRE_ASSURANCE,
	DIRECTION_RH,DIRECTION_FINANCIERE,DIRECTION_MARKETING,
	ENTREPRISE_PRIVE,ENTREPRISE_PUBLIC,PARTICULIER

}
