package tn.banque.Entities;

public enum TypeEmployee {
	/*0*/GESTIONNAIRE_CLIENTELE,
	/*1*/GESTIONNAIRE_PATRIMOINE,
	/*2*/CONSEILLER,
	/*3*/CONTROLLEUR_GESTION,
	/*4*/PARTENAIRE_ASSURANCE,
	/*5*/DIRECTION_RH,
	/*6*/DIRECTION_FINANCIERE,
	/*7*/DIRECTION_MARKETING,
	/*8*/ENTREPRISE_PRIVE,
	/*9*/ENTREPRISE_PUBLIC,
	/*10*/PARTICULIER,
	/*11*/Admin

}
